### ISSUE TITLE
Remove the dollar prefix

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/ContextData#11]
The current API has a dollar prefix in front of the type property. This isn’t a common convention in JavaScript, and is a little confusing!

(it also makes people think of jquery, which is not a good association to make!)

**Comment by rikoe** [comment]
The dollar prefix was added for two reasons:
* Disambiguation for objects that have their own "type" properties.
* To aid discovery in finding nested types in a larger type, e.g. finding the contact type representing a counterparty in a trade

I picked the $ prefix, maybe naively, because it was supported in TypeScript and JSON and seemed more concise and explicit than "fdc3Type" or "contextType".

I am happy to discuss alternatives.

**Comment by ColinEberhardt** [comment]
Thanks for sharing our reasoning.

Do we really need to disambiguate? By the same argument, should all our properties have some form of prefix?

In practice, if I have an object that already had a type property, whose data I wanted to use to represent a context, I’d simple create a new object specifically for this purpose, that conformed to this interface.

A dollar prefix is odd looking, and unusual, implying special behaviour, which is not the case here!

**Comment by tjratch** [comment]
I agree with @ColinEberhardt that when I see the dollar sign my mind immediately thinks of jQuery. I feel that to really disambiguate between the fdc3 and objects that have their own type projects, we should provide a more explicit hint to the developer. 

imagine the following:
```
{   
  type: instrument,
  $type: security
}
```

It's hard at a glace it's hard to to know that $type is fdc3-specific. The cue to the developer should say, "this is an fdc3 object" or "this should not be used internally". 

To say "this is an fdc3 object", we can add some sort of explicit prefix like "fdc3Type" or "fdc3_type". To say "this should not be used internally" we could borrow the javascript convention of using an underscore to discourage use like "_type"

Thoughts?

**Comment by rikoe** [comment]
I agree with these observations. The original proposal was for just "type", and that is what we are using today as well. I went with `$type` sort of the off-the-cuff based on feedback from people that "type" as a property may be too generic and hard to search for in a complex type composed of other types.

Happy to go back to just `type`, I think that is the cleanest. I agree @ColinEberhardt that my existing type can be adapted to match the schema, and when searching, so long as the schema is clear, it doesn't matter whether it is `type` or `$type`.

Also, it seems I will need to make an offering to the JavaScript gods for the blasphemy of using dollar as a prefix... 😉

**Comment by espenove** [comment]
Resolved in https://github.com/FDC3/ContextData/pull/15
